# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Modo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Modo
  pod 'NMapsMap'
  pod 'Alamofire'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'


  target 'ModoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModoUITests' do
    # Pods for testing
  end

  # temporary fix for this issue to suppress a ton of warnings
  # https://github.com/CocoaPods/CocoaPods/issues/7314
  post_install do |pi|
      pi.pods_project.targets.each do |t|
          t.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          end
      end
  end

end
